name: shadylauncher
license: GPL-3.0-only
base: core20
website: https://gitlab.com/KanuX/shadylauncher
source-code: https://gitlab.com/KanuX/shadylauncher
issues: https://gitlab.com/KanuX/shadylauncher/-/issues
donation: https://opencollective.com/prismlauncher
contact: https://discord.gg/prismlauncher
summary: A custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once.
adopt-info: shadylauncher

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  shadylauncher:
    parse-info:
      - usr/share/metainfo/org.shadylauncher.ShadyLauncher.metainfo.xml
    plugin: cmake
    build-packages:
      - default-jdk-headless
    stage-packages:
      - openjdk-17-jre
      - openjdk-8-jre
    source: .
    override-pull: |
      snapcraftctl pull
      # Fix the icon reference in the desktop file
      sed -i.bak -e 's|Icon=org.shadylauncher.ShadyLauncher|Icon=/usr/share/icons/hicolor/scalable/apps/org.shadylauncher.ShadyLauncher.svg|g' program_info/org.shadylauncher.ShadyLauncher.desktop.in
      # Remove the build directory so that local development doesn't interfere with Snap compilation
      rm -rf build
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
      - "-DENABLE_LTO=ON"
      - "-DLauncher_BUILD_PLATFORM=snap"
      - "-DLauncher_QT_VERSION_MAJOR=5"

apps:
  shadylauncher:
    common-id: org.shadylauncher.ShadyLauncher
    desktop: usr/share/applications/org.shadylauncher.ShadyLauncher.desktop
    command: usr/bin/shadylauncher
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - audio-playback
